{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "0c62c873-d5c1-497e-9af7-0c2d9fdc1099",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Create a list of customer names\n",
    "customer_names = [\n",
    "    \"Alice Johnson\",\n",
    "    \"Bob Smith\",\n",
    "    \"Charlie Davis\",\n",
    "    \"Diana Martinez\",\n",
    "    \"Ethan Brown\",\n",
    "    \"Fiona Wilson\",\n",
    "    \"George Taylor\",\n",
    "    \"Hannah Lee\",\n",
    "    \"Ivan Anderson\",\n",
    "    \"Julia Thomas\"\n",
    "]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "ea9eaec6-c97d-4e96-b228-eb22695a6377",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Store each customer's order details as tuples (customer_name, product, price, category)\n",
    "customer_orders = [\n",
    "    # Alice Johnson's orders\n",
    "    (\"Alice Johnson\", \"Laptop\", 850.00, \"Electronics\"),\n",
    "    (\"Alice Johnson\", \"Wireless Mouse\", 25.00, \"Electronics\"),\n",
    "    (\"Alice Johnson\", \"T-Shirt\", 15.00, \"Clothing\"),\n",
    "    \n",
    "    # Bob Smith's orders\n",
    "    (\"Bob Smith\", \"Smartphone\", 650.00, \"Electronics\"),\n",
    "    (\"Bob Smith\", \"Phone Case\", 20.00, \"Electronics\"),\n",
    "    \n",
    "    # Charlie Davis's orders\n",
    "    (\"Charlie Davis\", \"Jeans\", 45.00, \"Clothing\"),\n",
    "    (\"Charlie Davis\", \"Sneakers\", 80.00, \"Clothing\"),\n",
    "    (\"Charlie Davis\", \"Blender\", 55.00, \"Home Essentials\"),\n",
    "    \n",
    "    # Diana Martinez's orders\n",
    "    (\"Diana Martinez\", \"Coffee Maker\", 75.00, \"Home Essentials\"),\n",
    "    (\"Diana Martinez\", \"Bed Sheets\", 40.00, \"Home Essentials\"),\n",
    "    (\"Diana Martinez\", \"Pillow Set\", 30.00, \"Home Essentials\"),\n",
    "    \n",
    "    # Ethan Brown's orders\n",
    "    (\"Ethan Brown\", \"Gaming Console\", 450.00, \"Electronics\"),\n",
    "    (\"Ethan Brown\", \"Controller\", 60.00, \"Electronics\"),\n",
    "    (\"Ethan Brown\", \"Headphones\", 120.00, \"Electronics\"),\n",
    "    \n",
    "    # Fiona Wilson's orders\n",
    "    (\"Fiona Wilson\", \"Dress\", 55.00, \"Clothing\"),\n",
    "    (\"Fiona Wilson\", \"Handbag\", 85.00, \"Clothing\"),\n",
    "    \n",
    "    # George Taylor's orders\n",
    "    (\"George Taylor\", \"Microwave\", 95.00, \"Home Essentials\"),\n",
    "    (\"George Taylor\", \"Toaster\", 35.00, \"Home Essentials\"),\n",
    "    \n",
    "    # Hannah Lee's orders\n",
    "    (\"Hannah Lee\", \"Tablet\", 380.00, \"Electronics\"),\n",
    "    (\"Hannah Lee\", \"Tablet Cover\", 25.00, \"Electronics\"),\n",
    "    (\"Hannah Lee\", \"Jacket\", 90.00, \"Clothing\"),\n",
    "    \n",
    "    # Ivan Anderson's orders\n",
    "    (\"Ivan Anderson\", \"Running Shoes\", 110.00, \"Clothing\"),\n",
    "    \n",
    "    # Julia Thomas's orders\n",
    "    (\"Julia Thomas\", \"Smart Watch\", 280.00, \"Electronics\"),\n",
    "    (\"Julia Thomas\", \"Yoga Mat\", 30.00, \"Home Essentials\"),\n",
    "    (\"Julia Thomas\", \"Water Bottle\", 15.00, \"Home Essentials\"),\n",
    "    (\"Julia Thomas\", \"Sports Bra\", 35.00, \"Clothing\")\n",
    "]\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "7f356fc8-9a2c-44f0-8142-0dccbe2098cb",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "================================================================================\n",
      "TASK 1: CUSTOMER ORDERS STORED SUCCESSFULLY\n",
      "================================================================================\n",
      "\n",
      "Total customers: 10\n",
      "Total orders: 26\n",
      "\n",
      "Sample customer orders (first 3):\n",
      "1. ('Alice Johnson', 'Laptop', 850.0, 'Electronics')\n",
      "2. ('Alice Johnson', 'Wireless Mouse', 25.0, 'Electronics')\n",
      "3. ('Alice Johnson', 'T-Shirt', 15.0, 'Clothing')\n"
     ]
    }
   ],
   "source": [
    "# Create a dictionary where keys are customer names and values are lists of ordered products\n",
    "customer_product_dict = {}\n",
    "for order in customer_orders:\n",
    "    customer_name, product, price, category = order\n",
    "    if customer_name not in customer_product_dict:\n",
    "        customer_product_dict[customer_name] = []\n",
    "    customer_product_dict[customer_name].append({\n",
    "        'product': product,\n",
    "        'price': price,\n",
    "        'category': category\n",
    "    })\n",
    "\n",
    "print(\"=\" * 80)\n",
    "print(\"TASK 1: CUSTOMER ORDERS STORED SUCCESSFULLY\")\n",
    "print(\"=\" * 80)\n",
    "print(f\"\\nTotal customers: {len(customer_names)}\")\n",
    "print(f\"Total orders: {len(customer_orders)}\")\n",
    "print(\"\\nSample customer orders (first 3):\")\n",
    "for i, order in enumerate(customer_orders[:3], 1):\n",
    "    print(f\"{i}. {order}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "63959b4c-cd18-4aee-8e37-0d5f24d819d0",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "================================================================================\n",
      "TASK 2: PRODUCT CLASSIFICATION BY CATEGORY\n",
      "================================================================================\n",
      "\n",
      "Total unique products: 26\n",
      "\n",
      "Product Category Mapping:\n",
      "  • Bed Sheets: Home Essentials\n",
      "  • Blender: Home Essentials\n",
      "  • Coffee Maker: Home Essentials\n",
      "  • Controller: Electronics\n",
      "  • Dress: Clothing\n",
      "  • Gaming Console: Electronics\n",
      "  • Handbag: Clothing\n",
      "  • Headphones: Electronics\n",
      "  • Jacket: Clothing\n",
      "  • Jeans: Clothing\n",
      "  • Laptop: Electronics\n",
      "  • Microwave: Home Essentials\n",
      "  • Phone Case: Electronics\n",
      "  • Pillow Set: Home Essentials\n",
      "  • Running Shoes: Clothing\n",
      "  • Smart Watch: Electronics\n",
      "  • Smartphone: Electronics\n",
      "  • Sneakers: Clothing\n",
      "  • Sports Bra: Clothing\n",
      "  • T-Shirt: Clothing\n",
      "  • Tablet: Electronics\n",
      "  • Tablet Cover: Electronics\n",
      "  • Toaster: Home Essentials\n",
      "  • Water Bottle: Home Essentials\n",
      "  • Wireless Mouse: Electronics\n",
      "  • Yoga Mat: Home Essentials\n",
      "\n",
      "Unique Product Categories: {'Clothing', 'Electronics', 'Home Essentials'}\n",
      "Total Categories: 3\n"
     ]
    }
   ],
   "source": [
    "# Create a dictionary to map each product to its category\n",
    "product_category_mapping = {}\n",
    "for order in customer_orders:\n",
    "    customer_name, product, price, category = order\n",
    "    product_category_mapping[product] = category\n",
    "\n",
    "# Create a set of unique product categories\n",
    "unique_categories = set(order[3] for order in customer_orders)\n",
    "\n",
    "print(\"\\n\" + \"=\" * 80)\n",
    "print(\"TASK 2: PRODUCT CLASSIFICATION BY CATEGORY\")\n",
    "print(\"=\" * 80)\n",
    "print(f\"\\nTotal unique products: {len(product_category_mapping)}\")\n",
    "print(f\"\\nProduct Category Mapping:\")\n",
    "for product, category in sorted(product_category_mapping.items()):\n",
    "    print(f\"  • {product}: {category}\")\n",
    "\n",
    "print(f\"\\nUnique Product Categories: {unique_categories}\")\n",
    "print(f\"Total Categories: {len(unique_categories)}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "4e4a07cb-eb89-4c09-817e-19142ad2fb7c",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "================================================================================\n",
      "TASK 3: CUSTOMER SPENDING ANALYSIS\n",
      "================================================================================\n",
      "\n",
      "Customer Spending Summary:\n",
      "--------------------------------------------------------------------------------\n",
      "Customer Name        Total Spending       Classification      \n",
      "--------------------------------------------------------------------------------\n",
      "Alice Johnson        $         890.00    High-Value Buyer    \n",
      "Bob Smith            $         670.00    High-Value Buyer    \n",
      "Charlie Davis        $         180.00    High-Value Buyer    \n",
      "Diana Martinez       $         145.00    High-Value Buyer    \n",
      "Ethan Brown          $         630.00    High-Value Buyer    \n",
      "Fiona Wilson         $         140.00    High-Value Buyer    \n",
      "George Taylor        $         130.00    High-Value Buyer    \n",
      "Hannah Lee           $         495.00    High-Value Buyer    \n",
      "Ivan Anderson        $         110.00    High-Value Buyer    \n",
      "Julia Thomas         $         360.00    High-Value Buyer    \n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "Customer Distribution by Classification:\n",
      "  • High-Value Buyer: 10 customers (100.0%)\n",
      "  • Moderate Buyer: 0 customers (0.0%)\n",
      "  • Low-Value Buyer: 0 customers (0.0%)\n"
     ]
    }
   ],
   "source": [
    "# Calculate total amount each customer spends and classify them\n",
    "customer_spending = {}\n",
    "customer_classification = {}\n",
    "\n",
    "for customer in customer_names:\n",
    "    total_spent = 0.0\n",
    "    if customer in customer_product_dict:\n",
    "        for order in customer_product_dict[customer]:\n",
    "            total_spent += order['price']\n",
    "    \n",
    "    customer_spending[customer] = total_spent\n",
    "    \n",
    "    # Classify customers based on spending\n",
    "    if total_spent > 100:\n",
    "        customer_classification[customer] = \"High-Value Buyer\"\n",
    "    elif 50 <= total_spent <= 100:\n",
    "        customer_classification[customer] = \"Moderate Buyer\"\n",
    "    else:\n",
    "        customer_classification[customer] = \"Low-Value Buyer\"\n",
    "\n",
    "print(\"\\n\" + \"=\" * 80)\n",
    "print(\"TASK 3: CUSTOMER SPENDING ANALYSIS\")\n",
    "print(\"=\" * 80)\n",
    "print(\"\\nCustomer Spending Summary:\")\n",
    "print(\"-\" * 80)\n",
    "print(f\"{'Customer Name':<20} {'Total Spending':<20} {'Classification':<20}\")\n",
    "print(\"-\" * 80)\n",
    "for customer in sorted(customer_names):\n",
    "    spending = customer_spending[customer]\n",
    "    classification = customer_classification[customer]\n",
    "    print(f\"{customer:<20} ${spending:>15.2f}    {classification:<20}\")\n",
    "\n",
    "# Count customers by classification\n",
    "classification_counts = {\n",
    "    \"High-Value Buyer\": 0,\n",
    "    \"Moderate Buyer\": 0,\n",
    "    \"Low-Value Buyer\": 0\n",
    "}\n",
    "for classification in customer_classification.values():\n",
    "    classification_counts[classification] += 1\n",
    "\n",
    "print(\"\\n\" + \"-\" * 80)\n",
    "print(\"Customer Distribution by Classification:\")\n",
    "for classification, count in classification_counts.items():\n",
    "    percentage = (count / len(customer_names)) * 100\n",
    "    print(f\"  • {classification}: {count} customers ({percentage:.1f}%)\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "9da64e7b-bec2-442c-8f9a-45dc02bb002b",
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'unique_products' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[31m---------------------------------------------------------------------------\u001b[39m",
      "\u001b[31mNameError\u001b[39m                                 Traceback (most recent call last)",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[6]\u001b[39m\u001b[32m, line 4\u001b[39m\n\u001b[32m      1\u001b[39m \u001b[38;5;66;03m# TASK 4: GENERATE BUSINESS INSIGHTS\u001b[39;00m\n\u001b[32m----> \u001b[39m\u001b[32m4\u001b[39m \u001b[38;5;28mprint\u001b[39m(\u001b[33mf\u001b[39m\u001b[33m\"\u001b[39m\u001b[33mTotal unique products: \u001b[39m\u001b[38;5;132;01m{\u001b[39;00m\u001b[38;5;28mlen\u001b[39m(\u001b[43munique_products\u001b[49m)\u001b[38;5;132;01m}\u001b[39;00m\u001b[33m\"\u001b[39m)\n\u001b[32m      5\u001b[39m \u001b[38;5;28;01mfor\u001b[39;00m i, product \u001b[38;5;129;01min\u001b[39;00m \u001b[38;5;28menumerate\u001b[39m(\u001b[38;5;28msorted\u001b[39m(unique_products), \u001b[32m1\u001b[39m):\n\u001b[32m      6\u001b[39m     \u001b[38;5;28mprint\u001b[39m(\u001b[33mf\u001b[39m\u001b[33m\"\u001b[39m\u001b[33m  \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mi\u001b[38;5;132;01m}\u001b[39;00m\u001b[33m. \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mproduct\u001b[38;5;132;01m}\u001b[39;00m\u001b[33m\"\u001b[39m)\n",
      "\u001b[31mNameError\u001b[39m: name 'unique_products' is not defined"
     ]
    }
   ],
   "source": [
    "# TASK 4: GENERATE BUSINESS INSIGHTS\n",
    "\n",
    "\n",
    "print(f\"Total unique products: {len(unique_products)}\")\n",
    "for i, product in enumerate(sorted(unique_products), 1):\n",
    "    print(f\"  {i}. {product}\")\n",
    "# Calculate total revenue per product category\n",
    "category_revenue = {}\n",
    "for order in customer_orders:\n",
    "    customer_name, product, price, category = order\n",
    "    if category not in category_revenue:\n",
    "        category_revenue[category] = 0.0\n",
    "    category_revenue[category] += price\n",
    "\n",
    "# Extract unique products using a set\n",
    "unique_products = set(order[1] for order in customer_orders)\n",
    "\n",
    "# Use list comprehension to find all customers who purchased electronics\n",
    "electronics_customers = [\n",
    "    order[0] for order in customer_orders \n",
    "    if order[3] == \"Electronics\"\n",
    "]\n",
    "# Get unique electronics customers\n",
    "unique_electronics_customers = list(set(electronics_customers))\n",
    "\n",
    "# Identify top 3 highest-spending customers\n",
    "sorted_customers = sorted(\n",
    "    customer_spending.items(), \n",
    "    key=lambda x: x[1], \n",
    "    reverse=True\n",
    ")\n",
    "top_3_customers = sorted_customers[:3]\n",
    "\n",
    "print(\"\\n\" + \"=\" * 80)\n",
    "print(\"TASK 4: BUSINESS INSIGHTS\")\n",
    "print(\"=\" * 80)\n",
    "\n",
    "# Revenue per category\n",
    "print(\"\\n1. TOTAL REVENUE PER PRODUCT CATEGORY:\")\n",
    "print(\"-\" * 80)\n",
    "total_revenue = sum(category_revenue.values())\n",
    "sorted_categories = sorted(category_revenue.items(), key=lambda x: x[1], reverse=True)\n",
    "for category, revenue in sorted_categories:\n",
    "    percentage = (revenue / total_revenue) * 100\n",
    "    print(f\"  • {category:<20}: ${revenue:>10.2f} ({percentage:>5.1f}% of total)\")\n",
    "print(f\"\\n  TOTAL REVENUE: ${total_revenue:.2f}\")\n",
    "\n",
    "# Unique products\n",
    "print(\"\\n2. UNIQUE PRODUCTS ORDERED:\")\n",
    "print(\"-\" * 80)\n",
    "# Electronics customers\n",
    "print(\"\\n3. CUSTOMERS WHO PURCHASED ELECTRONICS:\")\n",
    "print(\"-\" * 80)\n",
    "print(f\"Total customers who bought electronics: {len(unique_electronics_customers)}\")\n",
    "for i, customer in enumerate(sorted(unique_electronics_customers), 1):\n",
    "    print(f\"  {i}. {customer}\")\n",
    "\n",
    "# Top 3 highest-spending customers\n",
    "print(\"\\n4. TOP 3 HIGHEST-SPENDING CUSTOMERS:\")\n",
    "print(\"-\" * 80)\n",
    "for i, (customer, spending) in enumerate(top_3_customers, 1):\n",
    "    print(f\"  {i}. {customer:<20} - ${spending:.2f}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "eb89988b-35d1-4ad6-bac8-352cbabab7ca",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "================================================================================\n",
      "TASK 5: ORGANIZED DATA DISPLAY\n",
      "================================================================================\n",
      "\n",
      "1. DETAILED CUSTOMER SUMMARY:\n",
      "--------------------------------------------------------------------------------\n",
      "\n",
      "Alice Johnson:\n",
      "  Total Spending: $890.00\n",
      "  Classification: High-Value Buyer\n",
      "  Products Purchased:\n",
      "    - Laptop ($850.00) - Electronics\n",
      "    - Wireless Mouse ($25.00) - Electronics\n",
      "    - T-Shirt ($15.00) - Clothing\n",
      "\n",
      "Bob Smith:\n",
      "  Total Spending: $670.00\n",
      "  Classification: High-Value Buyer\n",
      "  Products Purchased:\n",
      "    - Smartphone ($650.00) - Electronics\n",
      "    - Phone Case ($20.00) - Electronics\n",
      "\n",
      "Charlie Davis:\n",
      "  Total Spending: $180.00\n",
      "  Classification: High-Value Buyer\n",
      "  Products Purchased:\n",
      "    - Jeans ($45.00) - Clothing\n",
      "    - Sneakers ($80.00) - Clothing\n",
      "    - Blender ($55.00) - Home Essentials\n",
      "\n",
      "Diana Martinez:\n",
      "  Total Spending: $145.00\n",
      "  Classification: High-Value Buyer\n",
      "  Products Purchased:\n",
      "    - Coffee Maker ($75.00) - Home Essentials\n",
      "    - Bed Sheets ($40.00) - Home Essentials\n",
      "    - Pillow Set ($30.00) - Home Essentials\n",
      "\n",
      "Ethan Brown:\n",
      "  Total Spending: $630.00\n",
      "  Classification: High-Value Buyer\n",
      "  Products Purchased:\n",
      "    - Gaming Console ($450.00) - Electronics\n",
      "    - Controller ($60.00) - Electronics\n",
      "    - Headphones ($120.00) - Electronics\n",
      "\n",
      "Fiona Wilson:\n",
      "  Total Spending: $140.00\n",
      "  Classification: High-Value Buyer\n",
      "  Products Purchased:\n",
      "    - Dress ($55.00) - Clothing\n",
      "    - Handbag ($85.00) - Clothing\n",
      "\n",
      "George Taylor:\n",
      "  Total Spending: $130.00\n",
      "  Classification: High-Value Buyer\n",
      "  Products Purchased:\n",
      "    - Microwave ($95.00) - Home Essentials\n",
      "    - Toaster ($35.00) - Home Essentials\n",
      "\n",
      "Hannah Lee:\n",
      "  Total Spending: $495.00\n",
      "  Classification: High-Value Buyer\n",
      "  Products Purchased:\n",
      "    - Tablet ($380.00) - Electronics\n",
      "    - Tablet Cover ($25.00) - Electronics\n",
      "    - Jacket ($90.00) - Clothing\n",
      "\n",
      "Ivan Anderson:\n",
      "  Total Spending: $110.00\n",
      "  Classification: High-Value Buyer\n",
      "  Products Purchased:\n",
      "    - Running Shoes ($110.00) - Clothing\n",
      "\n",
      "Julia Thomas:\n",
      "  Total Spending: $360.00\n",
      "  Classification: High-Value Buyer\n",
      "  Products Purchased:\n",
      "    - Smart Watch ($280.00) - Electronics\n",
      "    - Yoga Mat ($30.00) - Home Essentials\n",
      "    - Water Bottle ($15.00) - Home Essentials\n",
      "    - Sports Bra ($35.00) - Clothing\n",
      "\n",
      "2. CUSTOMERS WHO PURCHASED FROM MULTIPLE CATEGORIES:\n",
      "--------------------------------------------------------------------------------\n",
      "  • Alice Johnson: Clothing, Electronics\n",
      "  • Charlie Davis: Clothing, Home Essentials\n",
      "  • Hannah Lee: Clothing, Electronics\n",
      "  • Julia Thomas: Clothing, Electronics, Home Essentials\n",
      "\n",
      "3. CUSTOMERS WHO BOUGHT BOTH ELECTRONICS AND CLOTHING:\n",
      "--------------------------------------------------------------------------------\n",
      "  1. Alice Johnson\n",
      "  2. Hannah Lee\n",
      "  3. Julia Thomas\n",
      "\n",
      "================================================================================\n",
      "ADDITIONAL BUSINESS INSIGHTS\n",
      "================================================================================\n",
      "\n",
      "1. AVERAGE ORDER VALUE BY CATEGORY:\n",
      "--------------------------------------------------------------------------------\n"
     ]
    },
    {
     "ename": "NameError",
     "evalue": "name 'category_revenue' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[31m---------------------------------------------------------------------------\u001b[39m",
      "\u001b[31mNameError\u001b[39m                                 Traceback (most recent call last)",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[12]\u001b[39m\u001b[32m, line 72\u001b[39m\n\u001b[32m     69\u001b[39m         category_order_count[category] = \u001b[32m0\u001b[39m\n\u001b[32m     70\u001b[39m     category_order_count[category] += \u001b[32m1\u001b[39m\n\u001b[32m---> \u001b[39m\u001b[32m72\u001b[39m \u001b[38;5;28;01mfor\u001b[39;00m category \u001b[38;5;129;01min\u001b[39;00m \u001b[38;5;28msorted\u001b[39m(\u001b[43mcategory_revenue\u001b[49m.keys()):\n\u001b[32m     73\u001b[39m     avg_order = category_revenue[category] / category_order_count[category]\n\u001b[32m     74\u001b[39m     \u001b[38;5;28mprint\u001b[39m(\u001b[33mf\u001b[39m\u001b[33m\"\u001b[39m\u001b[33m  • \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mcategory\u001b[38;5;132;01m:\u001b[39;00m\u001b[33m<20\u001b[39m\u001b[38;5;132;01m}\u001b[39;00m\u001b[33m: $\u001b[39m\u001b[38;5;132;01m{\u001b[39;00mavg_order\u001b[38;5;132;01m:\u001b[39;00m\u001b[33m.2f\u001b[39m\u001b[38;5;132;01m}\u001b[39;00m\u001b[33m\"\u001b[39m)\n",
      "\u001b[31mNameError\u001b[39m: name 'category_revenue' is not defined"
     ]
    }
   ],
   "source": [
    "# TASK 5: ORGANIZE AND DISPLAY DATA\n",
    "\n",
    "\n",
    "print(\"\\n\" + \"=\" * 80)\n",
    "print(\"TASK 5: ORGANIZED DATA DISPLAY\")\n",
    "print(\"=\" * 80)\n",
    "\n",
    "# Print summary of each customer's spending and classification\n",
    "print(\"\\n1. DETAILED CUSTOMER SUMMARY:\")\n",
    "print(\"-\" * 80)\n",
    "for customer in sorted(customer_names):\n",
    "    print(f\"\\n{customer}:\")\n",
    "    print(f\"  Total Spending: ${customer_spending[customer]:.2f}\")\n",
    "    print(f\"  Classification: {customer_classification[customer]}\")\n",
    "    if customer in customer_product_dict:\n",
    "        print(f\"  Products Purchased:\")\n",
    "        for order in customer_product_dict[customer]:\n",
    "            print(f\"    - {order['product']} (${order['price']:.2f}) - {order['category']}\")\n",
    "\n",
    "# Find customers who purchased from multiple categories\n",
    "print(\"\\n2. CUSTOMERS WHO PURCHASED FROM MULTIPLE CATEGORIES:\")\n",
    "print(\"-\" * 80)\n",
    "multi_category_customers = {}\n",
    "for customer in customer_names:\n",
    "    if customer in customer_product_dict:\n",
    "        categories = set(order['category'] for order in customer_product_dict[customer])\n",
    "        if len(categories) > 1:\n",
    "            multi_category_customers[customer] = categories\n",
    "\n",
    "for customer, categories in sorted(multi_category_customers.items()):\n",
    "    print(f\"  • {customer}: {', '.join(sorted(categories))}\")\n",
    "\n",
    "# Find common customers who bought both Electronics and Clothing\n",
    "print(\"\\n3. CUSTOMERS WHO BOUGHT BOTH ELECTRONICS AND CLOTHING:\")\n",
    "print(\"-\" * 80)\n",
    "electronics_buyers = set()\n",
    "clothing_buyers = set()\n",
    "\n",
    "for order in customer_orders:\n",
    "    customer_name, product, price, category = order\n",
    "    if category == \"Electronics\":\n",
    "        electronics_buyers.add(customer_name)\n",
    "    elif category == \"Clothing\":\n",
    "        clothing_buyers.add(customer_name)\n",
    "\n",
    "# Set intersection to find common customers\n",
    "both_categories = electronics_buyers.intersection(clothing_buyers)\n",
    "\n",
    "if both_categories:\n",
    "    for i, customer in enumerate(sorted(both_categories), 1):\n",
    "        print(f\"  {i}. {customer}\")\n",
    "else:\n",
    "    print(\"  No customers purchased from both categories\")\n",
    "\n",
    "\n",
    "# ADDITIONAL ANALYSIS & INSIGHTS\n",
    "\n",
    "print(\"\\n\" + \"=\" * 80)\n",
    "print(\"ADDITIONAL BUSINESS INSIGHTS\")\n",
    "print(\"=\" * 80)\n",
    "\n",
    "# Average order value per category\n",
    "print(\"\\n1. AVERAGE ORDER VALUE BY CATEGORY:\")\n",
    "print(\"-\" * 80)\n",
    "category_order_count = {}\n",
    "for order in customer_orders:\n",
    "    category = order[3]\n",
    "    if category not in category_order_count:\n",
    "        category_order_count[category] = 0\n",
    "    category_order_count[category] += 1\n",
    "\n",
    "for category in sorted(category_revenue.keys()):\n",
    "    avg_order = category_revenue[category] / category_order_count[category]\n",
    "    print(f\"  • {category:<20}: ${avg_order:.2f}\")\n",
    "\n",
    "# Most popular product by frequency\n",
    "print(\"\\n2. MOST FREQUENTLY PURCHASED PRODUCTS:\")\n",
    "print(\"-\" * 80)\n",
    "product_frequency = {}\n",
    "for order in customer_orders:\n",
    "    product = order[1]\n",
    "    product_frequency[product] = product_frequency.get(product, 0) + 1\n",
    "\n",
    "sorted_products = sorted(product_frequency.items(), key=lambda x: x[1], reverse=True)\n",
    "for i, (product, count) in enumerate(sorted_products[:5], 1):\n",
    "    print(f\"  {i}. {product}: {count} purchase(s)\")\n",
    "\n",
    "# Revenue contribution by customer type\n",
    "print(\"\\n3. REVENUE CONTRIBUTION BY CUSTOMER TYPE:\")\n",
    "print(\"-\" * 80)\n",
    "classification_revenue = {\n",
    "    \"High-Value Buyer\": 0.0,\n",
    "    \"Moderate Buyer\": 0.0,\n",
    "    \"Low-Value Buyer\": 0.0\n",
    "}\n",
    "\n",
    "for customer, classification in customer_classification.items():\n",
    "    classification_revenue[classification] += customer_spending[customer]\n",
    "\n",
    "for classification in [\"High-Value Buyer\", \"Moderate Buyer\", \"Low-Value Buyer\"]:\n",
    "    revenue = classification_revenue[classification]\n",
    "    percentage = (revenue / total_revenue) * 100\n",
    "    print(f\"  • {classification:<20}: ${revenue:.2f} ({percentage:.1f}% of total)\")\n",
    "\n",
    "\n",
    "# SUMMARY STATISTICS\n",
    "\n",
    "\n",
    "print(\"\\n\" + \"=\" * 80)\n",
    "print(\"FINAL SUMMARY STATISTICS\")\n",
    "print(\"=\" * 80)\n",
    "\n",
    "average_customer_spending = sum(customer_spending.values()) / len(customer_names)\n",
    "\n",
    "print(f\"\\nTotal Revenue: ${total_revenue:.2f}\")\n",
    "print(f\"Total Customers: {len(customer_names)}\")\n",
    "print(f\"Total Orders: {len(customer_orders)}\")\n",
    "print(f\"Total Unique Products: {len(unique_products)}\")\n",
    "print(f\"Total Product Categories: {len(unique_categories)}\")\n",
    "print(f\"Average Customer Spending: ${average_customer_spending:.2f}\")\n",
    "print(f\"Highest Spending Customer: {top_3_customers[0][0]} (${top_3_customers[0][1]:.2f})\")\n",
    "print(f\"Most Profitable Category: {sorted_categories[0][0]} (${sorted_categories[0][1]:.2f})\")\n",
    "\n",
    "print(\"\\n\" + \"=\" * 80)\n",
    "print(\"ANALYSIS COMPLETE\")\n",
    "print(\"=\" * 80)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "99953383-ffb0-4632-96f7-f4c9bb10eeea",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
